#Kubernetes Pod Creation (Pod with a single container)
apiVersion: v1   #This is api version
kind: Pod   #This is type of kubernetes controller, and it is Pod
metadata:   #metadata is a label block
  name: nginx1   #This is name of the Pod
spec:
  containers:
    - name: nginx   #This is container name
      image: nginx:1.14.2
      ports:
        - containerPort: 80
--- #kubernetes will understand --- as different config file
#Multi container Pod creation
apiVersion: v1
kind: Pod
metadata:         #metadata is a label block
  name: demo-mc   #creating pod with multi containers
spec:
  containers:
    - name: nginx   #contianer1
      image: nginx:1.19
      ports:
        - containerPort: 80
    - name: debug   #container2
      image: rkalluru/debug