#In the below example we are creating both replicaset with 3 pods with name frontend and one pod
#with name nginx-1 but both rs and Pod are have same label/tier as frontend. So, the replica
#contrrollerr will look for same label and the number of replicas, and will create the pods accordingly.
#but it will not create more than 3 pods as per below example. You can notice this in K9S tool.

#Creation of Pods using ReplicaSet
apiVersion: apps/v1
kind: ReplicaSet   #type of controller
metadata:
  name: rs-nginx   #name of the replicaset
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3   #Number of Pods to be created
  selector:    #this says to match all the pods with label/tier = frontend as ours
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:   #this is the spec of container, we have seen in Pod template
      containers:
        - name: php-redis
          image: nginx
---
#creating Pod with same label name "frontend"
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  labels:
    app: guestbook
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx:1.19
      ports:
        - containerPort: 80


