#This code is to show the limitation of the ReplicaSet
#ReplicaSet will not allow to modify some of the things like configuration changes.
#ReplicaSet will bother about only the number of Replicas are running or not
#ReplicaSet will not bother about the configuration changes done to the pod
#In the below example, we are creating 3 pods with nginx:1.14.2 in Run-1
#Later, we are updating the configuration to nginx:1:15 in Run-2
#But ReplicaSet will not re-create the pods with new configuration
#Instead it will continue with old configuration pods
#You can notice this in K9S tool
apiVersion: apps/v1
kind: ReplicaSet   #type of controller
metadata:
  name: frontend   #name of the replicaset
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3   #Number of Pods to be created
  selector:    #this says to match all the pods with label/tier = frontend as ours
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:   #this is the spec of container, we have seen in Pod template
      containers:
        - name: php-redis
          #image: nginx:1.14.2    # Run-1 = 1.14.2
          image: nginx:1:15      # Run-2 = 1:15
