#Creation of Pods using ReplicaSet
apiVersion: apps/v1
kind: ReplicaSet   #type of controller
metadata:
  name: frontend   #name of the replicaset
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3   #Number of Pods to be created
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:   #this is the spec of container, we have seen in Pod template
      containers:
        - name: php-redis
          image: nginx
---
#creating Pod with same label name "frontend"
apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  labels:
    app: guestbook
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx:1.19
      ports:
        - containerPort: 80


