#Pods Scale-up Strategy or Controlling Pods Rotation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 30 #number of replicas
  selector:
    matchLabels:
      app: nginx
  strategy:                  #rollong/controlling update strategy
    rollingUpdate:
      maxSurge: 1%
      maxUnavailable: 1%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
         #image: nginx:1.15    #Run1
          image: nginx:1.17    #Run2
          ports:
            - containerPort: 80
