#Creating deployment
apiVersion: apps/v1
kind: Deployment   #type of controller
metadata:
  name: nginx-deployment   #name of deployment
  labels:
    app: nginx
spec:
  replicas: 3   #number of replicas
  selector:
    matchLabels:
      app: nginx #selector to match pods with label = nginx
  template:
    metadata:
      labels:
        app: nginx  #pod name
    spec:
      containers:
        - name: nginx  #pod container name
          image: nginx:1.14.2    #Run1
         #image: nginx:1:15      #Run2 - Here the pods will be re-created with 1:15 config
          ports:
            - containerPort: 80
