#Creating deployment
apiVersion: apps/v1
kind: Deployment   #type of controller
metadata:
  name: nginx-deployment   #name of deployment
  labels:
    app: nginx
spec:
  replicas: 3   #number of replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
