#Code to create job
apiVersion: batch/v1
kind: Job   #type of controller
metadata:
  name: pi   #name of the job
spec:
  template:   #contianer template
    spec:
      containers:
        - name: pi
          image: perl:5.34.0
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never  #don't restart the job if it gets completed successfully
  backoffLimit: 4   #run the job up to 4 times if it gets failed
