#Cronjob example
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello   #name of the job
spec:
  schedule: "* * * * *"    # to run the job at every minute, for more details http://crontab.guru
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox:1.28
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
