#code to create LoadBalancer service
apiVersion: v1
kind: Pod
metadata:
  name: nginx-lb
  labels:
    appName: nginx
    demoFor: nginx-lb
spec:
  containers:
    - name: nginx
      image: nginx:1.19
      ports:
        - containerPort: 80
---
#code to create LoadBalancer service
apiVersion: v1
kind: Service   #Says it is a service
metadata:
  name: nginx-lb   #name of the service
spec:
  type: LoadBalancer   #type of the service
  selector:
    appName: nginx
    demoFor: nginx-lb  #we are keeping the same name so that same name labels will get pickup
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80