# This is the copy of 05-service-cip.yml
# I just made some changes in this code so that it is easily understandable

apiVersion: v1
kind: Service
metadata:
  name: nginx-cip-svc    #made a change here
spec:
  selector:
    appName: nginx
    demoFor: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-cip-pod    #made a change here
  labels:
    appName: nginx
    demoFor: ClusterIP
spec:
  containers:
    - name: nginx
      image: nginx:1.19
      ports:
        - containerPort: 80