apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-demo
data:
  URL: google.com
---
apiVersion: v1
kind: Pod
metadata:
  name: cm-demo-1
spec:
  containers:
    - name: debug
      image: rkalluru/debug
      env:                       # Define the environment variable
        - name: URL              # Notice that the case is different here
          valueFrom:
            configMapKeyRef:
              name: cm-demo      # This is the ConfigMap name to refer.
              key: URL           # This is the key to fetch from ConfigMap.
