apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-demo
data:
  URL: google.com
  domain: www.google.com
  company: google
---
apiVersion: v1
kind: Pod
metadata:
  name: cm-demo-1
spec:
  containers:
  - name: debug
    image: rkalluru/debug
    env:                       # Define the environment variable
      - name: URL          # Notice that the case is different here
        valueFrom:
          configMapKeyRef:
            name: cm-demo      # This is the ConfigMap name to refer.
            key: URL           # This is the key to fetch from ConfigMap.
---
apiVersion: v1
kind: Pod
metadata:
  name: cm-demo-2
spec:
  containers:
  - name: debug
    image: rkalluru/debug
    envFrom:                       # Define the environment variable
      - configMapRef:
          name: cm-demo           # This is the ConfigMap name to refer.
