apiVersion: v1
kind: Secret
metadata:
  name: secret-demo
data:
  message: SGVsbG8gV29ybGQ=
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-3
spec:
  containers:
    - name: debug
      image: rkalluru/debug
      volumeMounts:
        - name: foo
          mountPath: "/data"
          readOnly: true
  volumes:
    - name: foo
      secret:
        secretName: secret-demo
        optional: true