---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    nname: example
  name: example
---
apiVersion: v1
kind: Pod
metadata:
  name: debug1-13-np
  namespace: example
  labels:
    podName: debug1-13-np
spec:
  containers:
  - name: debug
    image: rkalluru/debug:latest
    resources:
      requests:
        cpu: 200m
        memory: 200Mi
      limits:
        cpu: 300m
        memory: 512Mi
    securityContext:
      allowPrivilegeEscalation: false  #means, this pod is not allowed to have any extra privileges in the system
      readOnlyRootFilesystem: true
      seccompProfile:
        type: RuntimeDefault
      runAsUser: 20000
      runAsGroup: 20000
      runAsNonRoot: true
      capabilities:
        drop:
          - ALL
---
apiVersion: v1
kind: LimitRange
metadata:
  name: debug1-13-np
  namespace: example
  labels:
    podName: debug1-13-np
spec:
  limits:
    - default: # this section defines default limits
        cpu: 300m
      defaultRequest: # this section defines default requests
        cpu: 200m
      max: # max and min define the limit range
        cpu: 300m
      min:
        cpu: 200m
      type: Container
---