apiVersion: v1
kind: Pod
metadata:
  name: node-selector-18
  labels:
    env: test
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
#   nodeSelector:
#     disktype: ssd

#kubectl label nodes aks-default-21207884-vmss000001 disktyp=ssd