apiVersion: v1
kind: Pod
metadata:
  name: tolerations-19
  labels:
    env: test
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent
#Run-1
  nodeSelector:
    disktype: ssd