{{ if .Values.debugPod.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: debug-{{ .Values.podName }}   ### we will pass this value dynamically
spec:
  containers:
  - name: debug
    image: rkalluru/debug
{{ end }}
